apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-ollama
  namespace: team-researchops
  labels:
    team: team-researchops
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 11434
  accessPolicy:
    inbound:
      rules:
        - application: reops-felgen
          namespace: team-researchops
  liveness:
    path: /api/version
    initialDelay: 60
    port: 11434
  readiness:
    path: /api/tags
    initialDelay: 60
    port: 11434
  resources:
    limits:
      memory: 7Gi
    requests:
      cpu: 500m
      memory: 5Gi
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 80
  ingresses:
    - "https://ollama.ansatt.nav.no"
    - "https://ollama.intern.nav.no"
