apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  name: reops-ollama
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{image}}
  port: 11434
  accessPolicy:
    outbound:
      external:
        - host: registry.ollama.ai
          ports:
            - port: 443
        - host: ollama.com
          ports:
            - port: 443
        - host: cloudflarestorage.com
          ports:
            - port: 443
        - host: dd20bb891979d25aebc8bec07b2b3bbc.r2.cloudflarestorage.com
          ports:
            - port: 443
        - host: r2.cloudflarestorage.com
          ports:
            - port: 443
  liveness:
    path: /api/tags
    initialDelay: 60
    port: 11434
  readiness:
    path: /api/tags
    initialDelay: 60
    port: 11434
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - "https://ollama.ansatt.nav.no"
    - "https://ollama.intern.nav.no"